package dz.solc.myviews.uitls;

public class Constans {


    public static final String testJson1 = "{\n" +
            "\n" +
            "\t\"code\": 1,\n" +
            "\n" +
            "\t\"data\": [{\n" +
            "\t\t\"job\": \"软件工程师\",\n" +
            "\t\t\"createdTime\": \"2018-6-10\",\n" +
            "\t\t\"name\": \"张三\",\n" +
            "\t\t\"money\": \"6k\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"测试人员\",\n" +
            "\t\t\"createdTime\": \"2018-6-11\",\n" +
            "\t\t\"name\": \"李四\",\n" +
            "\t\t\"money\": \"7kianisnfiasnfjasnfjansfnanfajnfansfasnfjansjfnasjfnjasnfjnubfuasbfuasbfausbfa\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"产品经理\",\n" +
            "\t\t\"createdTime\": \"2018-6-12\",\n" +
            "\t\t\"name\": \"王五\",\n" +
            "\t\t\"money\": \"15k\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"市场营销\",\n" +
            "\t\t\"createdTime\": \"2018-6-6\",\n" +
            "\t\t\"name\": \"王二腻\",\n" +
            "\t\t\"money\": \"8kasdadasdasdsadsadasd515151515112312sd5151515151123123sd5151515151123123sd5151515151123123sd515151515112312332351.\"\n" +
            "\t}]\n" +
            "\n" +
            "}";

    public static final String testJson = "[{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三522f\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 666\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            "]";


    public static final String testData = " [{\n" +
            "\t\t\"id\": 121,\n" +
            "\t\t\"createdTime\": 1572969900,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"modifiedTime\": 1573004324,\n" +
            "\t\t\"modifiedBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 0.3100,\n" +
            "\t\t\"dipY\": -0.2300,\n" +
            "\t\t\"dipXRate\": -118.4300,\n" +
            "\t\t\"dipYRate\": -23.4900,\n" +
            "\t\t\"dipXChange\": 0.0000,\n" +
            "\t\t\"dipYChange\": 0.0000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1572883200\n" +
            "\t}, {\n" +
            "\t\t\"id\": 137,\n" +
            "\t\t\"createdTime\": 1573056300,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"modifiedTime\": 1573121868,\n" +
            "\t\t\"modifiedBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 0.3100,\n" +
            "\t\t\"dipY\": -0.2300,\n" +
            "\t\t\"dipXRate\": 0.0000,\n" +
            "\t\t\"dipYRate\": 0.0000,\n" +
            "\t\t\"dipXChange\": 0.0000,\n" +
            "\t\t\"dipYChange\": 0.0000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1572969600\n" +
            "\t}, {\n" +
            "\t\t\"id\": 200,\n" +
            "\t\t\"createdTime\": 1573142700,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 0.3300,\n" +
            "\t\t\"dipY\": -0.2400,\n" +
            "\t\t\"dipXRate\": 0.0200,\n" +
            "\t\t\"dipYRate\": -0.0100,\n" +
            "\t\t\"dipXChange\": 0.0200,\n" +
            "\t\t\"dipYChange\": -0.0100,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1573056000\n" +
            "\t}, {\n" +
            "\t\t\"id\": 241,\n" +
            "\t\t\"createdTime\": 1573315500,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 0.3300,\n" +
            "\t\t\"dipY\": -0.2400,\n" +
            "\t\t\"dipXRate\": 0.0000,\n" +
            "\t\t\"dipYRate\": 0.0000,\n" +
            "\t\t\"dipXChange\": 0.0000,\n" +
            "\t\t\"dipYChange\": 0.0000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1573228800\n" +
            "\t}, {\n" +
            "\t\t\"id\": 364,\n" +
            "\t\t\"createdTime\": 1573833900,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 17.5900,\n" +
            "\t\t\"dipY\": 21.1020,\n" +
            "\t\t\"dipXRate\": 17.5900,\n" +
            "\t\t\"dipYRate\": 21.1020,\n" +
            "\t\t\"dipXChange\": 0.0000,\n" +
            "\t\t\"dipYChange\": 0.0000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1573747200\n" +
            "\t}, {\n" +
            "\t\t\"id\": 422,\n" +
            "\t\t\"createdTime\": 1574093100,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 18.5000,\n" +
            "\t\t\"dipY\": 22.3020,\n" +
            "\t\t\"dipXRate\": 0.9100,\n" +
            "\t\t\"dipYRate\": 1.2000,\n" +
            "\t\t\"dipXChange\": 0.9100,\n" +
            "\t\t\"dipYChange\": 1.2000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1574006400\n" +
            "\t}, {\n" +
            "\t\t\"id\": 442,\n" +
            "\t\t\"createdTime\": 1574179500,\n" +
            "\t\t\"createdBy\": 1,\n" +
            "\t\t\"flag\": 1,\n" +
            "\t\t\"device\": {\n" +
            "\t\t\t\"code\": \"QJ20190903001\",\n" +
            "\t\t\t\"name\": \"倾角传感器\"\n" +
            "\t\t},\n" +
            "\t\t\"dipX\": 18.5000,\n" +
            "\t\t\"dipY\": 22.3020,\n" +
            "\t\t\"dipXRate\": 0.0000,\n" +
            "\t\t\"dipYRate\": 0.0000,\n" +
            "\t\t\"dipXChange\": 0.0000,\n" +
            "\t\t\"dipYChange\": 0.0000,\n" +
            "\t\t\"state\": \"3,3\",\n" +
            "\t\t\"dataTime\": 1574092800\n" +
            "\t}]";
}
