package dz.solc.myviews.uitls;

public class Constans {


    public static final String testJson1 = "{\n" +
            "\n" +
            "\t\"code\": 1,\n" +
            "\n" +
            "\t\"data\": [{\n" +
            "\t\t\"job\": \"软件工程师\",\n" +
            "\t\t\"createdTime\": \"2018-6-10\",\n" +
            "\t\t\"name\": \"张三\",\n" +
            "\t\t\"money\": \"6k\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"测试人员\",\n" +
            "\t\t\"createdTime\": \"2018-6-11\",\n" +
            "\t\t\"name\": \"李四\",\n" +
            "\t\t\"money\": \"7k\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"产品经理\",\n" +
            "\t\t\"createdTime\": \"2018-6-12\",\n" +
            "\t\t\"name\": \"王五\",\n" +
            "\t\t\"money\": \"10k\"\n" +
            "\t}, {\n" +
            "\t\t\"job\": \"市场营销\",\n" +
            "\t\t\"createdTime\": \"2018-6-6\",\n" +
            "\t\t\"name\": \"王二腻\",\n" +
            "\t\t\"money\": \"8k\"\n" +
            "\t}]\n" +
            "\n" +
            "}";

    public static final String testJson = "[{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "},{\n" +
            "\t\"id\": 28169,\n" +
            "\t\"createdTime\": 1557476551,\n" +
            "\t\"createdBy\": \"张三\",\n" +
            "\t\"name\": \"ID\",\n" +
            "\t\"ls\": 6\n" +
            "}, {\n" +
            "\t\"id\": 28172,\n" +
            "\t\"createdTime\": 1557476552,\n" +
            "\t\"createdBy\": \"李四\",\n" +
            "\t\"name\": \"时间\",\n" +
            "\t\"ls\": 7\n" +
            "}, {\n" +
            "\t\"id\": 28175,\n" +
            "\t\"createdTime\": 1557476553,\n" +
            "\t\"createdBy\": \"王五\",\n" +
            "\t\"name\": \"专家\",\n" +
            "\t\"ls\": 8\n" +
            "}, {\n" +
            "\t\"id\": 28178,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"麻子\",\n" +
            "\t\"name\": \"辅助\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            ", {\n" +
            "\t\"id\": 282434,\n" +
            "\t\"createdTime\": 1557476554,\n" +
            "\t\"createdBy\": \"oksod\",\n" +
            "\t\"name\": \"23ksnmd\",\n" +
            "\t\"ls\": 9\n" +
            "}\n" +
            "]";
}
